python train_net.py 0
python train_net.py 1
python train_net.py 2
python train_net.py 3
python train_net.py 4
python train_net.py 5
python train_net.py 6
python train_net.py 7
python train_net.py 8
python train_net.py 9
